services:
  - type: web
    name: interview-ai-backend
    env: node
    rootDir: Backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_ORIGIN
        value: https://interview-ai-frontend.onrender.com
      - key: MONGO_DB
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false

  - type: static
    name: interview-ai-frontend
    rootDir: Frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://interview-ai-backend.onrender.com
